from utils import ingest_file

def run_ingestion_script():
    ingest_file("/Users/uday/Desktop/dodgeai-task-python/data.jsonl", "accountingDocument")

    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/billing_document_cancellations/part-20251119-133433-51.jsonl", "billingDocument")
    # print("Ingested billing_document_cancellations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/billing_document_headers/part-20251119-133433-228.jsonl", "billingDocument")
    # print("Ingested billing_document_headers")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/billing_document_headers/part-20251119-133433-936.jsonl", "billingDocument")
    # print("Ingested billing_document_headers")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/billing_document_items/part-20251119-133432-233.jsonl", "billingDocument")
    # print("Ingested billing_document_items")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/billing_document_items/part-20251119-133432-978.jsonl", "billingDocument")
    # print("Ingested billing_document_items")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/business_partners/part-20251119-133435-168.jsonl", "businessPartner")
    # print("Ingested business_partners")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/customer_company_assignments/part-20251119-133436-59.jsonl", "customer")
    # print("Ingested customer_company_assignments")
    # # customer_sales_area_assignments
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/customer_sales_area_assignments/part-20251119-133437-884.jsonl", "customer")
    # print("Ingested customer_sales_area_assignments")
    # # journal_entry_items_accounts_receivable
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/journal_entry_items_accounts_receivable/part-20251119-133433-74.jsonl", "accountingDocument")
    # print("Ingested journal_entry_items_accounts_receivable")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/journal_entry_items_accounts_receivable/part-20251119-133434-273.jsonl", "accountingDocument")
    # print("Ingested journal_entry_items_accounts_receivable")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/journal_entry_items_accounts_receivable/part-20251119-133434-581.jsonl", "accountingDocument")
    # print("Ingested journal_entry_items_accounts_receivable")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/journal_entry_items_accounts_receivable/part-20251119-133434-669.jsonl", "accountingDocument")
    # print("Ingested journal_entry_items_accounts_receivable")
    # # outbound_delivery_headers
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/outbound_delivery_headers/part-20251119-133431-414.jsonl", "deliveryDocument")
    # print("Ingested outbound_delivery_headers")
    # # outbound_delivery_items
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/outbound_delivery_items/part-20251119-133431-439.jsonl", "deliveryDocument")
    # print("Ingested outbound_delivery_items")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/outbound_delivery_items/part-20251119-133431-626.jsonl", "deliveryDocument")
    # print("Ingested outbound_delivery_items")
    # # payments_accounts_receivable
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/payments_accounts_receivable/part-20251119-133434-100.jsonl", "accountingDocument")
    # print("Ingested payments_accounts_receivable")
    # # plants
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/plants/part-20251119-133445-279.jsonl", "plant")
    # print("Ingested plants")
    # # product descriptions
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_descriptions/part-20251119-133438-106.jsonl", "product")
    # print("Ingested product descriptions")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_descriptions/part-20251119-133438-991.jsonl", "product")
    # print("Ingested product descriptions")
    # # product plants
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_plants", "product")
    # print("Ingested product plants")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_plants/part-20251119-133439-488.jsonl", "product")
    # print("Ingested product plants")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_plants/part-20251119-133439-814.jsonl", "product")
    # print("Ingested product plants")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_plants/part-20251119-133440-467.jsonl ", "product")
    # print("Ingested product plants")
    # # product stoage locations
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133440-440.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133440-895.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133441-19.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133441-417.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133441-547.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133441-889.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133442-95.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133442-116.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133442-150.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133442-967.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133443-6.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133443-26.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133443-270.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133443-397.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133444-49.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133444-294.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133444-415.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/product_storage_locations/part-20251119-133445-881.jsonl", "storageLocation")
    # print("Ingested product storage locations")
    # # products
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/products/part-20251119-133438-390.jsonl", "product")
    # print("Ingested products")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/products/part-20251119-133438-730.jsonl", "product")
    # print("Ingested products")
    # # sales_order_headers
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/sales_order_headers/part-20251119-133429-440.jsonl", "salesOrder")
    # print("Ingested sales order headers")
    # # sales_order_items
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/sales_order_items/part-20251119-133429-452.jsonl", "salesOrder")
    # print("Ingested sales order items")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/sales_order_items/part-20251119-133430-214.jsonl", "salesOrder")
    # print("Ingested sales order items")
    # # sales_order_schedule_lines
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/sales_order_schedule_lines/part-20251119-133430-302.jsonl", "salesOrder")
    # print("Ingested sales order schedule lines")
    # ingest_file("/Users/uday/Desktop/dodgeai-task-python/data/sales_order_schedule_lines/part-20251119-133430-979.jsonl", "salesOrder")
    # print("Ingested sales order schedule lines")